### ISSUE TITLE
Make nubers on balls larger

### ISSUE THREAD

**Issue by MagSG-7274** [7274-dev/AdventnaVyzva-Stranka#8]
Its really hard to find the correct number on the ball when the numbers are so small. Make em bigger

**Comment by ivanhrabcak** [comment]
It is very hard to choose the size for them, especially on mobile. Because the balls are different on each device (it's mostly noticeable in mobile) it's very hard to chose a font size that fits into balls on all screen sizes, let alone which looks good. :(

**Comment by Magiccop990** [comment]
:(

**Comment by Streamer272** [comment]
We can not do anything about this, so may I close this issue?
