### ISSUE TITLE
DevTools are Broken

### ISSUE THREAD

**Issue by Magiccop990** [7274-dev/AdventnaVyzva-Stranka#9]
DevTools don't work properly, i get access granted dialog, but it doesn't let me open locked windows

**Comment by ivanhrabcak** [comment]
DevTools right now work only when you try to use them for the first time. You can work around this by deleting your cookies.
Should be resolved easily

**Comment by Streamer272** [comment]
I tried to fix it, should be done now

**Comment by Streamer272** [comment]
see this commit: e5d9290
then decide if we want to finally close this issue
